---

- name: "VLAN Playbook"
  hosts: cisco
  connection: network_cli

  tasks:
    - name: "Push Cisco VLAN config"
      cisco.ios.ios_vlans:
        config:
        - name: FIVE
          vlan_id: 5
          state: active
          shutdown: disabled
        - name: TEN
          vlan_id: 10
          state: active
          shutdown: disabled
        state: overridden
      register: "cisco_output"


    - name: "Print Cisco output"
      debug:
        msg: "{{ cisco_output }}"
